import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Main</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <div>
        <h1 className="bg-red-500 p-6">sam namu 인덱스 page</h1>
      </div>
    </div>
  );
}
